services:
  app:
    build: "./app"
    ports:
      - "3000:3000"
    networks:
      - webnet

  app2:
    build: "./app2"
    ports:
      - "3001:3001"
    networks:
      - webnet

  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - app
      - app2
    networks:
      - webnet

networks:
  webnet:
